const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = new Schema({
    dbContractReferenceNumber: { type: String, unique: true, required: true },
    dbRequestorEmployeeID: { type: String, required: true },
    dbRequestorFullName: { type: String, required: true },
    dbRequestorEmail: { type: String, required: true },
    dbPayingCostCentre: { type: String, required: true },
    dbLegalEntity: { type: String, required: true },
    dbBusinessFunctiondrivingrequirementfortheBusinessCase: { type: String, required: true },
    dbRegion: { type: String, required: true },
    dbDateofRequest: { type: String, required: true, value: Date.now() },
    dbSpendType: { type: String, required: true },
    dbITCommodityCategory: { type: String, required: true },
    dbProjectorInitiativeTitle: { type: String, required: true },
    dbSpendTaxonomy: { type: String, required: true },
    dbBudgetIdentificationnumber: { type: String, required: true },
    dbIsthereaninflationintherenewal: { type: String, required: true },
    dbInflationjustification: { type: String, required: true },
    dbProcurementContact: { type: String, required: true },
    dbProcurementCasenumber: { type: String, required: true },
    dbVendorName: { type: String, required: true },
    dbVendorRelationship: { type: String, required: true },
    dbVendorCategory: { type: String, required: true },
    dbSpendDescription: { type: String, required: true },
    dbQualitativeBenefits: { type: String, required: true },
    dbQualintitativeBenefits: { type: String, required: true },
    dbAlternativesconsideredduringvendororprojectselection: { type: String, required: true },
    dbProjectBenefits: { type: String, required: true },
    dbContractLength: { type: String, required: true },
    dbHasamultiyeardealbeenconsidered: { type: String, required: true },
    dbIsthisprogrammeincludedinZBB: { type: String, required: true },
    dbZBBUniquelinesreferencenumbers: { type: String, required: true },
    dbIsthereaHeadwindasaresultofthisinitiative: { type: String, required: true },
    dbHeadwindvalueforcurrentfinancialyear: { type: String, required: true },
    dbHeadwindvaluefornextfinancialyear: { type: String, required: true },
    dbBusinessFunctionimpactedbytheHeadwind: { type: String, required: true },
    dbHeadwindforecastID: { type: String, required: true },
    dbPrevious12monthscontractvalue: { type: String, required: true },
    dbLenghoftermofpreviouscontract: { type: String, required: true },
    dbMaintenance: { type: String, required: true },
    dbJustificationifmaintenanceisabovesetthreshold: { type: String, required: true },
    dbArchitectureApprovalReferenceNumber: { type: String, required: true },
    dbSpendEffectivedate: { type: String, required: true },
    dbCapExdepreciationperiod: { type: String, required: true },
    dbTotalCapEx: { type: String, required: true },
    dbTotalOpEx: { type: String, required: true },
    dbYear1: { type: String, required: true },
    dbYear1OpEx: { type: String, required: true },
    dbYear1Depreciation: { type: String, required: true },
    dbYear2OpEx: { type: String, required: true },
    dbYear2Depreciation: { type: String, required: true },
    dbYear3OpEx: { type: String, required: true },
    dbYear3Depreciation: { type: String, required: true },
    dbYear4OpEx: { type: String, required: true },
    dbYear4Depreciation: { type: String, required: true },
    dbYear5OpEx: { type: String, required: true },
    dbYear5Depreciation: { type: String, required: true },
    dbYear6OpEx: { type: String, required: true },
    dbYear6Depreciation: { type: String, required: true },
    dbYear6Depreciation: { type: String, required: true },
    dbcreatedDate: { type: Date, required: true, default: Date.now }
});

schema.set('toJSON', { virtuals: true });

module.exports = mongoose.model('Proposal', schema);